// Our movie model
class Movie {
  final int id, year, numOfRatings, criticsReview, metascoreRating;
  final double rating;
  final List<String> genra;
  final String plot, title, poster, backdrop;
  final List<Map> cast;

  Movie({
    required this.poster,
    required this.backdrop,
    required this.title,
    required this.id,
    required this.year,
    required this.numOfRatings,
    required this.criticsReview,
    required this.metascoreRating,
    required this.rating,
    required this.genra,
    required this.plot,
    required this.cast,
  });
}

// our demo data movie data
List<Movie> movies = [
  Movie(
    id: 1,
    title: "Mad Max",
    year: 2015,
    poster: "assets/images/poster_4.jpg",
    backdrop: "assets/images/backdrop-4.jpg",
    numOfRatings: 150212,
    rating: 8.9,
    criticsReview: 50,
    metascoreRating: 79,
    genra: ["Action", "Drama", "Adrenalin"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 1,
    title: "Bloodshot",
    year: 2020,
    poster: "assets/images/poster_1.jpg",
    backdrop: "assets/images/backdrop_1.jpg",
    numOfRatings: 150212,
    rating: 7.3,
    criticsReview: 50,
    metascoreRating: 76,
    genra: ["Action", "Drama"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 2,
    title: "Ford v Ferrari ",
    year: 2019,
    poster: "assets/images/poster_2.jpg",
    backdrop: "assets/images/backdrop_2.jpg",
    numOfRatings: 150212,
    rating: 8.2,
    criticsReview: 50,
    metascoreRating: 76,
    genra: ["Action", "Biography", "Drama"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 1,
    title: "Onward",
    year: 2020,
    poster: "assets/images/poster_3.jpg",
    backdrop: "assets/images/backdrop_3.jpg",
    numOfRatings: 150212,
    rating: 7.6,
    criticsReview: 50,
    metascoreRating: 79,
    genra: ["Action", "Drama"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
];

List<Movie> movies2 = [
  Movie(
    id: 1,
    title: "Avengers Infinite War",
    year: 2020,
    poster: "assets/images/poster_5.jpg",
    backdrop: "assets/images/backdrop_5.jpg",
    numOfRatings: 150212,
    rating: 9.1,
    criticsReview: 50,
    metascoreRating: 76,
    genra: ["Action", "Drama", "Sci_fi"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 2,
    title: "How To Train Your Dragon ",
    year: 2018,
    poster: "assets/images/poster_7.jpg",
    backdrop: "assets/images/backdrop_7.jpg",
    numOfRatings: 150212,
    rating: 8.5,
    criticsReview: 50,
    metascoreRating: 76,
    genra: ["Comedy", "Family", "Drama"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 1,
    title: "Dark Knight",
    year: 2002,
    poster: "assets/images/poster_6.jpg",
    backdrop: "assets/images/backdrop_6.jpg",
    numOfRatings: 150212,
    rating: 9.2,
    criticsReview: 50,
    metascoreRating: 79,
    genra: ["Action", "Drama", "Crime", "Horror"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
];
List<Movie> movies3 = [
  Movie(
    id: 1,
    title: "The Lord Of The Ring",
    year: 2001,
    poster: "assets/images/poster_8.jpg",
    backdrop: "assets/images/backdrop_8.jpg",
    numOfRatings: 150212,
    rating: 9.3,
    criticsReview: 50,
    metascoreRating: 88,
    genra: ["Action", "Drama", "Fantacy"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 2,
    title: "The Hobbit ",
    year: 2014,
    poster: "assets/images/poster_9.jpg",
    backdrop: "assets/images/backdrop_9.jpg",
    numOfRatings: 150212,
    rating: 8.8,
    criticsReview: 50,
    metascoreRating: 85,
    genra: ["Comedy", "Fantacy", "Drama"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 1,
    title: "The Maze Runner ",
    year: 2012,
    poster: "assets/images/poster_10.jpg",
    backdrop: "assets/images/backdrop_10.jpg",
    numOfRatings: 150212,
    rating: 8.7,
    criticsReview: 50,
    metascoreRating: 81,
    genra: ["Action", "Drama"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
];
List<Movie> anime = [
  Movie(
    id: 1,
    title: "One Piece",
    year: 1998,
    poster: "assets/images/poster_11.jpg",
    backdrop: "assets/images/backdrop_11.jpg",
    numOfRatings: 150212,
    rating: 9.0,
    criticsReview: 50,
    metascoreRating: 95,
    genra: ["shonen", "Action", "Drama", "Comedy"],
    plot:
        "The world of One Piece is populated by humans and other races such as dwarves (more akin to faeries in size), giants, merfolk, fish-men, long-limbed tribes, long-necked people known as the Snakeneck Tribe, and animal people . The world is governed by an intercontinental organization known as the World Government, consisting of dozens of member countries. The Navy is the sea military branch of the World Government that protects the known seas from pirates and other criminals",
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 2,
    title: "Fulmetal Alchemist",
    year: 2005,
    poster: "assets/images/poster_14.jpg",
    backdrop: "assets/images/backdrop_14.jpg",
    numOfRatings: 150212,
    rating: 9.5,
    criticsReview: 50,
    metascoreRating: 90,
    genra: ["Comedy", "Fantacy", "Drama", "shonen"],
    plot:
        "Fullmetal Alchemist takes place in the fictional country of Amestris (アメストリス, Amesutorisu). In this world, alchemy is one of the most-practiced sciences; alchemists who work for the government are known as State Alchemists (国家錬金術師, Kokka Renkinjutsushi) and are automatically given the rank of major in the military. Alchemists have the ability, with the help of patterns called transmutation circles, to create almost anything they desire. However, when they do so, they must provide something of equal value in accordance with the Law of Equivalent Exchange",
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 3,
    title: "Code Geass ",
    year: 2008,
    poster: "assets/images/poster_12.jpg",
    backdrop: "assets/images/backdrop_12.jpg",
    numOfRatings: 150212,
    rating: 8.8,
    criticsReview: 50,
    metascoreRating: 86,
    genra: ["Action", "Drama", "Militery"],
    plot:
        "Lelouch vi Britannia is an exiled Britannian prince, son of Emperor Charles zi Britannia and his royal consort Marianne vi Britannia. Lelouch has a sister, Nunnally vi Britannia. Marianne was brutally murdered in the palace and Nunnally, who witnessed the murder of their mother, was so traumatized she lost both her sight and ability to walk. Lelouch is furious with his father, believing his father failed his mother and sister by turning a blind eye to their mother's death and failing to pursue their mother's killer.",
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 4,
    title: "Bleach ",
    year: 2002,
    poster: "assets/images/poster_13.jpg",
    backdrop: "assets/images/backdrop_13.jpg",
    numOfRatings: 150212,
    rating: 8.8,
    criticsReview: 50,
    metascoreRating: 86,
    genra: ["Action", "Drama", "Shonen"],
    plot:
        "high school student Ichigo Kurosaki becomes a substitute Soul Reaper (死神, Shinigami, literally, Death God), when Rukia Kuchiki risks her life to protect him from a Hollow. Although initially reluctant to accept his responsibility, he takes her place, and during this time they discover that a few classmates are spiritually aware and have their own powers: Quincy survivor Uryū Ishida uses spiritual particles, Orihime Inoue has a group of protective spirits called Shun Shun Rikka and Yasutora Sado  has strength equal to the Hollows encased in his arm.",
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 5,
    title: "Neon Genesis Evangleon ",
    year: 1975,
    poster: "assets/images/poster_15.jpg",
    backdrop: "assets/images/backdrop_15.png",
    numOfRatings: 150212,
    rating: 8.4,
    criticsReview: 50,
    metascoreRating: 86,
    genra: ["phsycological", "Drama", "Dark"],
    plot:
        "teenager Shinji Ikari is summoned to the futuristic city of Tokyo-3 by his estranged father Gendo Ikari, who is the director of the special paramilitary force Nerv. Shinji witnesses United Nations forces battling an Angel, one of a race of monstrous beings whose awakening was foretold in the Dead Sea Scrolls. Because of the Angels' near-impenetrable force fields, Nerv's Evangelion bio-machines, which are synchronized to their pilots' nervous systems and possess their own force fields, are the only weapons capable of fighting the Angels. Nerv officer Misato Katsuragi escorts Shinji into the Nerv complex beneath Tokyo-3, where Gendo pressures him into piloting Evangelion Unit-01 against the Angel. Without training, Shinji is quickly overwhelmed, causing the Evangelion to go berserk and savagely kill the Angel on its own.",
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
];
List<Movie> actionMovies = [
  Movie(
    id: 1,
    title: "Mad Max",
    year: 2015,
    poster: "assets/images/poster_4.jpg",
    backdrop: "assets/images/backdrop-4.jpg",
    numOfRatings: 150212,
    rating: 9.1,
    criticsReview: 50,
    metascoreRating: 95,
    genra: ["Action", "Adrenalin", "Cars"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 2,
    title: "The Dark Knight",
    year: 2002,
    poster: "assets/images/poster_6.jpg",
    backdrop: "assets/images/backdrop_6.jpg",
    numOfRatings: 150212,
    rating: 9.0,
    criticsReview: 50,
    metascoreRating: 89,
    genra: ["Action", "Drama", "Crime"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 3,
    title: "The Lord Of The Ring ",
    year: 2004,
    poster: "assets/images/poster_8.jpg",
    backdrop: "assets/images/backdrop_8.jpg",
    numOfRatings: 150212,
    rating: 9.6,
    criticsReview: 50,
    metascoreRating: 99,
    genra: ["Action", "Drama", "Fantasy"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 4,
    title: "The Maze Runner ",
    year: 2013,
    poster: "assets/images/poster_10.jpg",
    backdrop: "assets/images/backdrop_10.jpg",
    numOfRatings: 150212,
    rating: 8.9,
    criticsReview: 50,
    metascoreRating: 88,
    genra: ["Action", "Drama", "Plots"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 5,
    title: "Blood Shot ",
    year: 2020,
    poster: "assets/images/poster_1.jpg",
    backdrop: "assets/images/backdrop_1.jpg",
    numOfRatings: 150212,
    rating: 7.4,
    criticsReview: 50,
    metascoreRating: 75,
    genra: ["Action", "Fast"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
];
List<Movie> comedyMovies = [
  Movie(
    id: 1,
    title: "Dictator",
    year: 2012,
    poster: "assets/images/poster_18.jpg",
    backdrop: "assets/images/backdrop_18.jpg",
    numOfRatings: 150212,
    rating: 8.2,
    criticsReview: 50,
    metascoreRating: 79,
    genra: ["Comedy", "hilarious", "R+18"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 2,
    title: "Dumb and Dummber",
    year: 2000,
    poster: "assets/images/poster_17.jpg",
    backdrop: "assets/images/backdrop_17.jpg",
    numOfRatings: 150212,
    rating: 7.5,
    criticsReview: 50,
    metascoreRating: 77,
    genra: ["Comedy", "hilarious", "Stupid"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 3,
    title: "Horrible Bosses",
    year: 2013,
    poster: "assets/images/poster_19.jpg",
    backdrop: "assets/images/backdrop_19.jpg",
    numOfRatings: 150212,
    rating: 6.6,
    criticsReview: 50,
    metascoreRating: 65,
    genra: ["hilarious", "Sus", "R+18"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 4,
    title: "Grown Ups",
    year: 2013,
    poster: "assets/images/poster_16.jpg",
    backdrop: "assets/images/backdrop_16.jpg",
    numOfRatings: 150212,
    rating: 8.1,
    criticsReview: 50,
    metascoreRating: 77,
    genra: ["Comedy", "Family"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
];
List<Movie> dramaMovies = [
  Movie(
    id: 1,
    title: "Shawshank Redemption",
    year: 1998,
    poster: "assets/images/poster_20.jpg",
    backdrop: "assets/images/backdrop_20.jpg",
    numOfRatings: 150212,
    rating: 9.2,
    criticsReview: 50,
    metascoreRating: 98,
    genra: ["Drama", "life"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 2,
    title: "The God Father",
    year: 1995,
    poster: "assets/images/poster_21.jpg",
    backdrop: "assets/images/backdrop_21.jpg",
    numOfRatings: 150212,
    rating: 9.2,
    criticsReview: 50,
    metascoreRating: 98,
    genra: ["Drama", "Gang", "Tragedy"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 3,
    title: "Oppenheimer",
    year: 2023,
    poster: "assets/images/poster_22.jpg",
    backdrop: "assets/images/backdrop_22.jpg",
    numOfRatings: 150212,
    rating: 8.8,
    criticsReview: 50,
    metascoreRating: 91,
    genra: ["Drama", "History", "Politic", "Based_on_real"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 4,
    title: "The Imitation Game",
    year: 2013,
    poster: "assets/images/poster_23.jpg",
    backdrop: "assets/images/backdrop_23.jpg",
    numOfRatings: 150212,
    rating: 8.6,
    criticsReview: 50,
    metascoreRating: 85,
    genra: ["Drama", "Exp"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
];
List<Movie> fantasyMovies = [
  Movie(
    id: 1,
    title: "The Lord Of The Ring",
    year: 2001,
    poster: "assets/images/poster_8.jpg",
    backdrop: "assets/images/backdrop_8.jpg",
    numOfRatings: 150212,
    rating: 9.2,
    criticsReview: 50,
    metascoreRating: 98,
    genra: ["Fantasy", "Drama", "Action"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 2,
    title: "Avengers Infinite War",
    year: 2018,
    poster: "assets/images/poster_5.jpg",
    backdrop: "assets/images/backdrop_5.jpg",
    numOfRatings: 150212,
    rating: 9.2,
    criticsReview: 50,
    metascoreRating: 98,
    genra: ["Drama", "Fantasy", "Action", "Super Powers"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 3,
    title: "The Hobbit",
    year: 2023,
    poster: "assets/images/poster_9.jpg",
    backdrop: "assets/images/backdrop_9.jpg",
    numOfRatings: 150212,
    rating: 8.9,
    criticsReview: 50,
    metascoreRating: 88,
    genra: ["Drama", "Action", "Fantasy", ""],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 4,
    title: "The Maze Runner",
    year: 2013,
    poster: "assets/images/poster_10.jpg",
    backdrop: "assets/images/backdrop_10.jpg",
    numOfRatings: 150212,
    rating: 8.7,
    criticsReview: 50,
    metascoreRating: 85,
    genra: ["Drama", "Action"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
];
List<Movie> topAnmie = [
  Movie(
    id: 1,
    title: "One Piece",
    year: 1998,
    poster: "assets/images/poster_11.jpg",
    backdrop: "assets/images/backdrop_11.jpg",
    numOfRatings: 150212,
    rating: 9.0,
    criticsReview: 50,
    metascoreRating: 95,
    genra: ["shonen", "Action", "Drama", "Comedy"],
    plot:
        "The world of One Piece is populated by humans and other races such as dwarves (more akin to faeries in size), giants, merfolk, fish-men, long-limbed tribes, long-necked people known as the Snakeneck Tribe, and animal people . The world is governed by an intercontinental organization known as the World Government, consisting of dozens of member countries. The Navy is the sea military branch of the World Government that protects the known seas from pirates and other criminals",
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 2,
    title: "Fulmetal Alchemist",
    year: 2005,
    poster: "assets/images/poster_14.jpg",
    backdrop: "assets/images/backdrop_14.jpg",
    numOfRatings: 150212,
    rating: 9.5,
    criticsReview: 50,
    metascoreRating: 90,
    genra: ["Comedy", "Fantacy", "Drama", "shonen"],
    plot:
        "Fullmetal Alchemist takes place in the fictional country of Amestris (アメストリス, Amesutorisu). In this world, alchemy is one of the most-practiced sciences; alchemists who work for the government are known as State Alchemists (国家錬金術師, Kokka Renkinjutsushi) and are automatically given the rank of major in the military. Alchemists have the ability, with the help of patterns called transmutation circles, to create almost anything they desire. However, when they do so, they must provide something of equal value in accordance with the Law of Equivalent Exchange",
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 3,
    title: "Code Geass ",
    year: 2008,
    poster: "assets/images/poster_12.jpg",
    backdrop: "assets/images/backdrop_12.jpg",
    numOfRatings: 150212,
    rating: 8.8,
    criticsReview: 50,
    metascoreRating: 86,
    genra: ["Action", "Drama", "Militery"],
    plot:
        "Lelouch vi Britannia is an exiled Britannian prince, son of Emperor Charles zi Britannia and his royal consort Marianne vi Britannia. Lelouch has a sister, Nunnally vi Britannia. Marianne was brutally murdered in the palace and Nunnally, who witnessed the murder of their mother, was so traumatized she lost both her sight and ability to walk. Lelouch is furious with his father, believing his father failed his mother and sister by turning a blind eye to their mother's death and failing to pursue their mother's killer.",
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
];
List<Movie> topAction = [
  Movie(
    id: 1,
    title: "Mad Max",
    year: 2015,
    poster: "assets/images/poster_4.jpg",
    backdrop: "assets/images/backdrop-4.jpg",
    numOfRatings: 150212,
    rating: 9.1,
    criticsReview: 50,
    metascoreRating: 95,
    genra: ["Action", "Adrenalin", "Cars"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 2,
    title: "The Dark Knight",
    year: 2002,
    poster: "assets/images/poster_6.jpg",
    backdrop: "assets/images/backdrop_6.jpg",
    numOfRatings: 150212,
    rating: 9.0,
    criticsReview: 50,
    metascoreRating: 89,
    genra: ["Action", "Drama", "Crime"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 3,
    title: "The Lord Of The Ring ",
    year: 2004,
    poster: "assets/images/poster_8.jpg",
    backdrop: "assets/images/backdrop_8.jpg",
    numOfRatings: 150212,
    rating: 9.6,
    criticsReview: 50,
    metascoreRating: 99,
    genra: ["Action", "Drama", "Fantasy"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
];
List<Movie> topDrama = [
  Movie(
    id: 1,
    title: "Shawshank Redemption",
    year: 1998,
    poster: "assets/images/poster_20.jpg",
    backdrop: "assets/images/backdrop_20.jpg",
    numOfRatings: 150212,
    rating: 9.2,
    criticsReview: 50,
    metascoreRating: 98,
    genra: ["Drama", "life"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 2,
    title: "The God Father",
    year: 1995,
    poster: "assets/images/poster_21.jpg",
    backdrop: "assets/images/backdrop_21.jpg",
    numOfRatings: 150212,
    rating: 9.2,
    criticsReview: 50,
    metascoreRating: 98,
    genra: ["Drama", "Gang", "Tragedy"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 3,
    title: "Oppenheimer",
    year: 2023,
    poster: "assets/images/poster_22.jpg",
    backdrop: "assets/images/backdrop_22.jpg",
    numOfRatings: 150212,
    rating: 8.8,
    criticsReview: 50,
    metascoreRating: 91,
    genra: ["Drama", "History", "Politic", "Based_on_real"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
];
List<Movie> topComedy = [
  Movie(
    id: 1,
    title: "Dictator",
    year: 2012,
    poster: "assets/images/poster_18.jpg",
    backdrop: "assets/images/backdrop_18.jpg",
    numOfRatings: 150212,
    rating: 8.2,
    criticsReview: 50,
    metascoreRating: 79,
    genra: ["Comedy", "hilarious", "R+18"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 2,
    title: "Dumb and Dummber",
    year: 2000,
    poster: "assets/images/poster_17.jpg",
    backdrop: "assets/images/backdrop_17.jpg",
    numOfRatings: 150212,
    rating: 7.5,
    criticsReview: 50,
    metascoreRating: 77,
    genra: ["Comedy", "hilarious", "Stupid"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 3,
    title: "Horrible Bosses",
    year: 2013,
    poster: "assets/images/poster_19.jpg",
    backdrop: "assets/images/backdrop_19.jpg",
    numOfRatings: 150212,
    rating: 6.6,
    criticsReview: 50,
    metascoreRating: 65,
    genra: ["hilarious", "Sus", "R+18"],
    plot: plotText,
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
];
String plotText =
    "American car designer Carroll Shelby and driver Kn Miles battle corporate interference and the laws of physics to build a revolutionary race car for Ford in order.";
